title: JasLieb Portfolio
description: "My portfolio page"
baseurl: "/"
url: "https://jaslieb.github.io"

plugins:
  - jekyll-content-security-policy-generator

header_pages:
  - pages/home.md
  - pages/projects.md
  - pages/jobs.md
  - pages/education.md

style: dark

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
