title: JasLieb Portfolio
description: "My portfolio page"
baseurl: "/"
url: "https://jaslieb.github.io"

header_pages:
  - pages/home.md
  - pages/projects.md
  - pages/jobs.md
  - pages/education.md
  - pages/contact.md

style: dark

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
